# Estructuras de Datos simples

Es conveniente usar estructuras para almacenar datos, 
como tuplas, arreglos, o diccionarios.

Tipos de estructuras de datos que se cubren:

    1.Tuplas
    2.Diccionarios
    3.Arreglos



## Tuplas

Las tuplas son estructuras de datos que consisten en una colección de elementos y que no pueden actualizarse. En cambio a los arreglos y los diccionarios sí se les puede realizar modificaciones.


In [2]:
##Forma de declarar una tupla

materias=("matemáticas","japonés","español","computación")


("matemáticas", "japonés", "español", "computación")

In [3]:
#Forma de indexar una tupla
materias[1]

# Nótese que se indexan con la definición clásica de Números naturales


"matemáticas"

In [4]:
# Aquí se muestra cómo una tupla no puede ser actualizada
materias[1]="algebra"


LoadError: MethodError: no method matching setindex!(::NTuple{4, String}, ::String, ::Int64)

# Diccionarios

Son una colección de parejas asociadas de datos, donde un dato llamado llave está asociado a otro dato llamado valor. Al dato llamado valor se le accede y modifica por medio de su llave.

Estas colecciones de datos no están ordenadas, a diferencia de las tuplas y de los arreglos. Por lo que no pueden ser indexados

In [5]:
#Un buen ejemplo de un diccionario es una lista telefónica

mi_agenda= Dict("Arturia Pendragón" => "55 54579908", 
    "Constanze Amalie Von Braunschbank Albrechtsberger" => "55 57023195")


Dict{String, String} with 2 entries:
  "Arturia Pendragón"                                 => "55 54579908"
  "Constanze Amalie Von Braunschbank Albrechtsberger" => "55 57023195"

In [6]:
#Realizamos una consulta
mi_agenda["Arturia Pendragón"]

"55 54579908"

In [7]:
#Agregamos otro elemento al diccionario

mi_agenda["Iris"]="55 53070899"



"55 53070899"

In [8]:
mi_agenda

Dict{String, String} with 3 entries:
  "Arturia Pendragón"                                 => "55 54579908"
  "Constanze Amalie Von Braunschbank Albrechtsberger" => "55 57023195"
  "Iris"                                              => "55 53070899"

In [9]:
mi_agenda["nuevo"]="000 0002"


"000 0002"

In [10]:
mi_agenda

Dict{String, String} with 4 entries:
  "Arturia Pendragón"                                 => "55 54579908"
  "Constanze Amalie Von Braunschbank Albrechtsberger" => "55 57023195"
  "Iris"                                              => "55 53070899"
  "nuevo"                                             => "000 0002"

In [11]:
#Removemos un elemento del diccionario

pop!(mi_agenda,"nuevo");

In [12]:
mi_agenda

Dict{String, String} with 3 entries:
  "Arturia Pendragón"                                 => "55 54579908"
  "Constanze Amalie Von Braunschbank Albrechtsberger" => "55 57023195"
  "Iris"                                              => "55 53070899"

In [13]:
#Demostramos que los diccionarios no se los puede indexar
mi_agenda[1]

LoadError: KeyError: key 1 not found

## Arreglos

Los arreglos son colecciones ordenadas de datos, que pueden se indexados. A diferencia de las tuplas, los arreglos sí pueden ser modificados.

Podemos crear arreglos encerrando entre corchetes una colección de datos.

Sintaxis:

    [elemento1, elemento2, ...]
    
Por ejemplo, se pueden crear un arreglo para llevar el registro de los amigos que tiene una persona:


In [14]:
misAmigos = ["María", "Lucía", "Sofía", "Pedro", "Tomás","Alfredo"]

6-element Vector{String}:
 "María"
 "Lucía"
 "Sofía"
 "Pedro"
 "Tomás"
 "Alfredo"

O se puede utilizar para almacenar una secuencia de números

In [15]:
fibonacci = [1, 1, 2, 3, 5, 8, 13]

7-element Vector{Int64}:
  1
  1
  2
  3
  5
  8
 13

In [16]:
mezcla = [1, 1, 2, 3, "Tomás", "Marcos"]

6-element Vector{Any}:
 1
 1
 2
 3
  "Tomás"
  "Marcos"

In [17]:
misAmigos[6]

"Alfredo"

Se puede editar un elemento existente de un arreglo usando el indexado

In [18]:
misAmigos[6]="Carlos"

"Carlos"

También se pueden editar arreglos usando las funciones push! y pop!

push! añade un elemento al final de un arreglo

pop! remueve el último elemento de un arreglo


De esta manera se puede añadir otro número a nuestra secuencia de Fibonacci

In [19]:
push!(fibonacci,21)

8-element Vector{Int64}:
  1
  1
  2
  3
  5
  8
 13
 21

Y luego removerlo

In [20]:
pop!(fibonacci)

21

In [21]:
fibonacci

7-element Vector{Int64}:
  1
  1
  2
  3
  5
  8
 13

En Julia los arreglos unidimensionales reciben el nombre de vectores.

Mientras que los arreglos multidimencionales de mxn, reciben el nombre de matrices.

También pueden almacenar otros arreglos


In [22]:
#=Aquí por ejemplo vamos a hacer la declaración de un arreglo de arreglos, 
que es un arreglo que contiene elementos que son arreglos.

En este caso particular se declara un arreglo de arreglo de cadenas. Su
firma es un arreglo de una dimensión (vector) de arreglos de una dimensión 
(vector) que almacenan cadenas. 

Dicho de otra forma es arreglo es un arreglo de dos elementos, donde cada
elemento es un arreglo de 3 cadenas
=#

favoritos=[["chocolate", "leche", "huevos"],["gatos","aves","french puddles"]]

2-element Vector{Vector{String}}:
 ["chocolate", "leche", "huevos"]
 ["gatos", "aves", "french puddles"]

In [23]:
#= 
Mientras aquí se tiene un vector de vectores que almacenan enteros de 64 bits
=#

numbers = [[1, 2, 3],[4, 5],[6, 7, 8, 9]]

3-element Vector{Vector{Int64}}:
 [1, 2, 3]
 [4, 5]
 [6, 7, 8, 9]

In [24]:
#= La función rand permite generar matrices de mxn donde cada elemento es
un flotante entre 0 y 1, generado con números únicos pseudoaleatorios
=#
rand(4,3)

4×3 Matrix{Float64}:
 0.427306  0.232608   0.0815394
 0.654173  0.0280201  0.463646
 0.556565  0.979542   0.165882
 0.411545  0.0200134  0.541814

In [25]:
#=Aquí se utiliza rand() con la finalidad de generar un arreglo 
multidimensional tridimensional
=#

rand(4,3,2)

4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.975514  0.0190537  0.0524136
 0.837734  0.888464   0.477563
 0.993144  0.397881   0.620022
 0.432618  0.745196   0.288465

[:, :, 2] =
 0.975406  0.624727  0.0347257
 0.216466  0.599178  0.389502
 0.320223  0.428348  0.536963
 0.751216  0.193344  0.803462

In [26]:
#=Hay que tener cuidado con esta tipo declaración que se escribió para
intentar copiar un arreglo. Ya que no copia el  arreglo  fibonacci  en 
es_copia, más bien declara un nuevo nombre o sinónimo para la 
estructura de datos ya existente de fibonacci.
=#

es_copia=fibonacci


7-element Vector{Int64}:
  1
  1
  2
  3
  5
  8
 13

In [27]:
#=Aquí se modifica el primer elemento de es_copia. Sin embargo, dado que 
es sinónimo de fibonacci, lo que ocurrirá es que el arreglo fibonacci se 
verá alterado en su primer elemento
=#
es_copia[1]=404

404

In [28]:
#=Aquí se muestra que los cambios en fibonacci, realizados por medio de su
sinónimo. Tal y cómo se esperaba.

=#

fibonacci

7-element Vector{Int64}:
 404
   1
   2
   3
   5
   8
  13

In [30]:
# Se restaura a Fibonacci
fibonacci[1]= 1
fibonacci

7-element Vector{Int64}:
  1
  1
  2
  3
  5
  8
 13

In [32]:
#= Para definir un arreglo que sea la copia
de otro arreglo, se utiliza la función copy()
=#

es_copia=copy(fibonacci)

7-element Vector{Int64}:
  1
  1
  2
  3
  5
  8
 13

In [35]:
es_copia[1]=404

404

In [36]:
#=Aquí se observa que Fibonacci no fue actualizada
por lo que se realizó la copia exitosamente

=#

fibonacci

7-element Vector{Int64}:
  1
  1
  2
  3
  5
  8
 13

Ejercicios

In [37]:
#= 1)
=#
a_ray =[1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [39]:
push!(a_ray,4)

4-element Vector{Int64}:
 1
 2
 3
 4

In [43]:
pop!(a_ray)

4

In [44]:
a_ray

3-element Vector{Int64}:
 1
 2
 3

In [45]:
#=Cuando se declara un diccionario sin especificar su contenido,
este por defecto en Julia adquiere un tipo any para las llaves y para sus valores 
=#

a= Dict()

Dict{Any, Any}()

In [47]:
a[1]="hola"
a[2]=3432
a

Dict{Any, Any} with 2 entries:
  2 => 3432
  1 => "hola"

In [48]:
#=Cuando se define un diccionario con todas las llaves del mismo tipo 
y los valores para cada llave del mismo tipo. Julia define este diccionario 
con base en estos tipos por defecto. Sin que se puedan agregar parejas de datos
cuyos tipos no correspondan con estos tipos por defecto.

Tal y cómo se muestra a continuación:
=#

a=Dict("2342" => 1,"1234" =>2)


Dict{String, Int64} with 2 entries:
  "2342" => 1
  "1234" => 2

In [49]:
a[3]=4

LoadError: MethodError: Cannot `convert` an object of type Int64 to an object of type String
Closest candidates are:
  convert(::Type{String}, ::String) at essentials.jl:210
  convert(::Type{T}, ::T) where T<:AbstractString at strings/basic.jl:231
  convert(::Type{T}, ::AbstractString) where T<:AbstractString at strings/basic.jl:232
  ...

In [56]:
#= 
Para evitar esto, y hacer mezclas de datos
se tiene que especificar que los tipos para las llaves y sus valores son de tipo 
any.

Tal y cómo se muestra a continuación.
=#

a=Dict{Any,Any}(1 =>"casa")

#=Esta identación para especificar los tipos de un diccionario son válidos 
también para los arreglos

=#

Dict{Any, Any} with 1 entry:
  1 => "casa"

In [53]:
#= 2)

=#

agenda_flexible=Dict("Juana"=> 530201, "Amigos" => "55-2716")

Dict{String, Any} with 2 entries:
  "Juana"  => 530201
  "Amigos" => "55-2716"

In [54]:
agenda_flexible["Emergencia"]=911

911

In [63]:
a=[1,2,3]
b=Array(a) #Array construye un nuevo arreglo duplicando otro arreglo que reciba de entrada
b[1]=3
b==a

false

In [58]:
a

3-element Vector{Int64}:
 1
 2
 3

In [59]:
b

3-element Vector{Int64}:
 3
 2
 3

In [61]:
?Array

search: Array SubArray BitArray DenseArray StridedArray PermutedDimsArray



```
Array{T,N} <: AbstractArray{T,N}
```

`N`-dimensional dense array with elements of type `T`.

---

```
Array{T}(undef, dims)
Array{T,N}(undef, dims)
```

Construct an uninitialized `N`-dimensional [`Array`](@ref) containing elements of type `T`. `N` can either be supplied explicitly, as in `Array{T,N}(undef, dims)`, or be determined by the length or number of `dims`. `dims` may be a tuple or a series of integer arguments corresponding to the lengths in each dimension. If the rank `N` is supplied explicitly, then it must match the length or number of `dims`. See [`undef`](@ref).

# Examples

```julia-repl
julia> A = Array{Float64, 2}(undef, 2, 3) # N given explicitly
2×3 Array{Float64, 2}:
 6.90198e-310  6.90198e-310  6.90198e-310
 6.90198e-310  6.90198e-310  0.0

julia> B = Array{Float64}(undef, 2) # N determined by the input
2-element Array{Float64, 1}:
 1.87103e-320
 0.0
```

---

```
Array{T}(nothing, dims)
Array{T,N}(nothing, dims)
```

Construct an `N`-dimensional [`Array`](@ref) containing elements of type `T`, initialized with [`nothing`](@ref) entries. Element type `T` must be able to hold these values, i.e. `Nothing <: T`.

# Examples

```jldoctest
julia> Array{Union{Nothing, String}}(nothing, 2)
2-element Vector{Union{Nothing, String}}:
 nothing
 nothing

julia> Array{Union{Nothing, Int}}(nothing, 2, 3)
2×3 Matrix{Union{Nothing, Int64}}:
 nothing  nothing  nothing
 nothing  nothing  nothing
```

---

```
Array{T}(missing, dims)
Array{T,N}(missing, dims)
```

Construct an `N`-dimensional [`Array`](@ref) containing elements of type `T`, initialized with [`missing`](@ref) entries. Element type `T` must be able to hold these values, i.e. `Missing <: T`.

# Examples

```jldoctest
julia> Array{Union{Missing, String}}(missing, 2)
2-element Vector{Union{Missing, String}}:
 missing
 missing

julia> Array{Union{Missing, Int}}(missing, 2, 3)
2×3 Matrix{Union{Missing, Int64}}:
 missing  missing  missing
 missing  missing  missing
```


In [96]:
A = Array{Float32,2}([2.0 3.0
           4.0 3.0
           4.0 5.0])

3×2 Matrix{Float32}:
 2.0  3.0
 4.0  3.0
 4.0  5.0

In [98]:
#=
Aquí se hace uso de operaciones vectorizadas
 Favor de atender las siguientes observaciones:
=#

A .+= 0.6

3×2 Matrix{Float32}:
 3.2  4.2
 5.2  4.2
 5.2  6.2